services:
  - type: web
    name: spelletjeskamer
    runtime: node
    plan: free
    buildCommand: NODE_ENV=development npm run install:all && npm run build
    startCommand: NODE_ENV=production node server/dist/server/src/index.js
    envVars:
      - key: NODE_VERSION
        value: 22
